"""Create a baseline migrations

Revision ID: 0fb4332d7ee9
Revises: 
Create Date: 2023-09-16 03:02:16.335403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fb4332d7ee9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('method_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preprocessing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_seq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_model')
    # ### end Alembic commands ###
